spring:
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/air
      username: postgres
      password: 222222
    second:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/post
      username: postgres
      password: 111111

  aop:
    proxy-target-class: true