spring:
  datasource:
    master:
      driver-class-name: org.postgresql.Driver
      jdbc-url: xxxxx
      username: xxxx
      password: xxx
    second:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://xxx/xxx
      username: xxx
      password: xxxxx

  aop:
    proxy-target-class: true